name: Create_Thesis

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nikitadmitryuk/thesismagistr/latex

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: ghcr.io/nikitadmitryuk/thesismagistr/latex:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Compile Thesis
        shell: bash
        run: make release

      - name: Rename release files
        shell: bash
        run: |
          find . -maxdepth 1 -name '*.tex' -exec bash -c 'mv "${0%.tex}.pdf" "${0%.tex}-${GITHUB_REF#refs/*/}.pdf"' {} \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-v*.pdf
