name: Create_Thesis

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker.io/2109199812/docker-latex:latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile Thesis
        shell: bash
        run: make release

      - name: Rename release file
        shell: bash
        run: |
          for filename in $(find "$(pwd)" -maxdepth 1 -name '*.tex' -printf "%f\n" | sed -r "s/(.*).tex/\1/g"); do mv ${filename}.pdf ${filename}-${GITHUB_REF#refs/*/}.pdf; done
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-v*.pdf
