name: Create_Thesis

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/2109199812/docker-latex:latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile Thesis
        shell: bash
        run: make release

      - name: Rename release files
        shell: bash
        run: |
          find . -maxdepth 1 -name '*.tex' -exec bash -c 'mv "${0%.tex}.pdf" "${0%.tex}-${GITHUB_REF#refs/*/}.pdf"' {} \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *-v*.pdf
