
name: Create_ThesisMagistr

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker.io/2109199812/docker-latex:latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile diplom.tex
        shell: bash
        run: make diplom

      - name: Compile presentation.tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation.tex

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            diplom.pdf
            presentation.pdf
