# This is a basic workflow to help you get started with Actions

name: Create_ThesisMagister

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: LaTeX compilation
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: diplom
          # LaTeX engine to be used
          compiler: pdflatex

      - name: Cache diplom
        uses: actions/cache@v3
        with:
          path: diplom.pdf
          key: ${{ runner.os }}-${{ steps.get_version.outputs.out }}
